//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesWebSite.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movy
    {
        public Movy()
        {
            this.Reviews = new HashSet<Review>();
            this.ShoppingCarts = new HashSet<ShoppingCart>();
            this.Shows = new HashSet<Show>();
        }
    
        public int MovieID { get; set; }
        public int CategoryID { get; set; }
        public string MovieName { get; set; }
        public string Director { get; set; }
        public string MovieImage { get; set; }
        public decimal MovieCost { get; set; }
        public string Description { get; set; }
    
        public virtual MovieCategory MovieCategory { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; }
        public virtual ICollection<Show> Shows { get; set; }
    }
}
